security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG
    com:
      example: DEBUG

ribbon: # <---NEW SECTION
  IsSecure: false
